name: Renovate post updates
on:
  push:
    branches:
    - renovate/**

permissions:
  contents: write
  statuses: write
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          cache-dependency-path: "**/*.sum"
      - name: go build
        run: |
          make tidy
          make generate
          make build
      - name: git update
        uses: planetscale/ghcommit-action@v0.2.19
        id: commit
        with:
          commit_message: "post update after go dependencies updation"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: update status
        if: ${{ steps.commit.outputs.commit-hash != '' }}
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ steps.commit.outputs.commit-hash }} \
            -f state=success \
            -f context=renovate/post \
            -f description="Running..."
        env:
          GH_TOKEN: ${{ github.token }}
